dtb-$(CONFIG_MODEL_DREAMLTE) += exynos8895-dreamlte_eur_open_00.dtb exynos8895-dreamlte_eur_open_01.dtb exynos8895-dreamlte_eur_open_02.dtb exynos8895-dreamlte_eur_open_03.dtb exynos8895-dreamlte_eur_open_04.dtb exynos8895-dreamlte_eur_open_05.dtb exynos8895-dreamlte_eur_open_07.dtb exynos8895-dreamlte_eur_open_08.dtb exynos8895-dreamlte_eur_open_09.dtb exynos8895-dreamlte_eur_open_10.dtb
dtb-$(CONFIG_MODEL_DREAM2LTE) += exynos8895-dream2lte_eur_open_01.dtb exynos8895-dream2lte_eur_open_02.dtb exynos8895-dream2lte_eur_open_03.dtb exynos8895-dream2lte_eur_open_04.dtb exynos8895-dream2lte_eur_open_05.dtb exynos8895-dream2lte_eur_open_06.dtb exynos8895-dream2lte_eur_open_07.dtb exynos8895-dream2lte_eur_open_08.dtb exynos8895-dream2lte_eur_open_09.dtb exynos8895-dream2lte_eur_open_10.dtb

targets += dtbs
dtbs: $(addprefix $(obj)/, $(DTB_LIST))
